### ISSUE TITLE
Create your first PR

### ISSUE THREAD

**Issue by itsjustkevin** [cleancodeclub/tech_squad_flowchart#1]
To familiarize yourselves with the git flow, I would like each of you to do the following through the **command line interface**, not the Github UI:

If you are having trouble completing the task, take the time to review the git documentation, as reading documentation is a necessary skill to develop.

1. Fork this repository.
2. Clone this repository.
3. Create a local branch.
4. Contribute to README.md with your name and email under the contributors section.
5. Create a pull request with your README contribution. 
6. Mark the task completed in this issue.
7. Leave a comment under the issue saying `Done`

Task completed
- [x]  Shaun
- [x]  Ricardo
- [x]  Elijah
- [x]  David

**Comment by wismandl** [comment]
Done

**Comment by ricardo-gonzalez-villegas** [comment]
Done

**Comment by eseenandan** [comment]
Done

**Comment by eseenandan** [comment]
Done

**Comment by polleyoo** [comment]
Done
